version: "3"

services:
  travis:
    image: rcmoutinho/travis-cli
    volumes:
      - .:/app
      - ./.travis:/root/.travis
    network_mode: bridge

  ebook:
    image: asciidoctor/docker-asciidoctor
    volumes:
      - .:/documents/
    command: ./asc-startup.sh
    network_mode: bridge
